FROM cosmo0920/win32-api:latest
LABEL maintainer "Hiroshi Hatake <cosmo0920.wp@gmail.com>"
LABEL Description="win32-api building docker image"

# Ruby 3.2
COPY trunk-installers .

RUN cmd /c "C:\rubyinstaller-head-x86-20220118.exe" /silent /dir=c:\ruby32
RUN cmd /c "C:\rubyinstaller-head-x64-20220118.exe" /silent /dir=c:\ruby32-x64

RUN mkdir C:\pkg
COPY build-gem.bat C:\\build-gem.bat
ENTRYPOINT ["cmd"]
